name: Build for Windows
on:
  push:
  pull_request:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Restore vcpkg cache
        uses: actions/cache/restore@v3
        id: vcpkg-cache
        with:
          path: |
            C:/vcpkg/installed
            C:/vcpkg/packages
            C:/vcpkg/buildtrees
          key: vcpkg-cache-${{ runner.os }}

      - name: Install Triton
        run: |
          "`r`nset(VCPKG_BUILD_TYPE release)" | Add-Content "$env:VCPKG_INSTALLATION_ROOT\triplets\x64-windows-static.cmake"
          vcpkg install triton --triplet x64-windows-static

      - name: Save vcpkg cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: |
            C:/vcpkg/installed
            C:/vcpkg/packages
            C:/vcpkg/buildtrees
          key: vcpkg-cache-${{ runner.os }}

      - name: Download IDA SDK 9.2
        run: |
          Invoke-WebRequest -Uri "https://codeload.github.com/HexRaysSA/ida-sdk/zip/refs/tags/v9.2" -OutFile "ida-sdk-9.2.zip"
          Expand-Archive -Path "ida-sdk-9.2.zip" -DestinationPath "."
          New-Item -ItemType Directory -Force -Path "sdk"
          Move-Item -Path "ida-sdk-9.2" -Destination "sdk/ida-sdk-9.2"
      
      - name: Build Ponce for IDA SDK 9.2
        run: |
          cmake -S . -B build_x64_9.2 -DIDASDK_ROOT_DIR="./sdk/ida-sdk-9.2/src" -DSTATICLIB=ON -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64 -DVCPKG_TARGET_TRIPLET="x64-windows-static" -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
          cmake --build build_x64_9.2 --config Release --parallel 2
      
      - name: Upload built DLLs
        uses: actions/upload-artifact@v4
        with:
          name: ponce-windows-artifacts
          path: |
            build_x64_9.2/Release/Ponce64.dll

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: build
    steps:
      - name: Download all Windows arifacts
        uses: actions/download-artifact@v4
        with:
          path: ./my_artifacts

      - name: Set output
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build zip file
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          cd my_artifacts
          zip -r ../ponce-$RELEASE_VERSION-win.zip *

      - name: Upload Windows artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ponce-${{ steps.vars.outputs.tag }}-win.zip
          asset_name: ponce-${{ steps.vars.outputs.tag }}-win.zip
          asset_content_type: application/zip
